services:
  mongodb:
    image: mongo
    container_name: salon_mongo_container
    volumes:
      - mongo-data:/data/db
    ports:
      - "27018:27017"

  backend:
    image: janidu007/salon-backend:latest
    container_name: salon_backend_container
    ports:
      - "9090:9090"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DATABASE=salonAPI

  frontend:
    image: janidu007/salon-frontend:latest
    container_name: salon_frontend_container
    ports:
      - "80:5173"
    depends_on:
      - backend

volumes:
  mongo-data: